CREATE TABLE LIBRO 
	(COD_LIB CHAR(5 BYTE), 
	TITULO VARCHAR2(70 CHAR) NOT NULL, 
	ANYO NUMBER(4,0), --4 DIGITS, DE IXOS 0 HAN DE SER DECIMALS
	AUTOR VARCHAR2(80 CHAR) NOT NULL, 
	CONSTRAINT PK_LIBRO PRIMARY KEY (COD_LIB));
    
INSERT INTO LIBRO SELECT * FROM CS_LIBRO;    

CREATE TABLE PELICULA 
	(COD_PELI CHAR(5 BYTE), 
	TITULO VARCHAR2(70 CHAR) NOT NULL,
	ANYO NUMBER(4,0), 
	DURACION NUMBER(4,0) NOT NULL, 
	COD_LIB CHAR(5 BYTE), 
	DIRECTOR VARCHAR2(70 CHAR), 
	CHECK (duracion > 0), 
	CONSTRAINT PK_PELICULA PRIMARY KEY (COD_PELI),
	CONSTRAINT FK_PELICULA_LIBRO FOREIGN KEY (COD_LIB)
	  REFERENCES LIBRO (COD_LIB));
      
INSERT INTO PELICULA SELECT * FROM CS_PELICULA WHERE ANYO > 2000;

INSERT INTO ACTOR SELECT DISTINCT A.cod_act, A.nombre, A.fecha_nac, P.nombre 
                    FROM CS_Actor A, CS_Pais P, CS_Actua C, CS_Pelicula P
                    WHERE A.cod_pais = P.cod_pais AND C.cod_act = A.cod_act 
                        AND C.cod_peli = P.cod_peli AND P.anyo > 2000;    

DESCRIBE PELICULA;

SELECT * FROM ACTOR;

COMMIT;

INSERT INTO ACTUA SELECT A.cod_Act, A.cod_peli, A.papel FROM CS_ACTUA A, CS_PELICULA P
                            WHERE A.cod_peli = P.cod_peli AND P.anyo > 2000;

SELECT * FROM ACTUA
ORDER BY cod_act;
COMMIT;



